config/routes.rb
Motorika::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users
  resources :uploads, :except => [:index, :create]
  match 'addphoto/:id' => 'uploads#index', :as => "uploads", :via => [:get]
  match 'addphoto/:id' => 'uploads#create', :as => "uploads", :via => [:post]
  resources :adverts
  match 'about' => 'application#about'
  match 'alladverts' => 'adverts#list', :as => "alladverts"
  match 'blogs' => 'topics#list', :as => "alltopics"
  match 'add_advert_comments' => 'adverts#add_comment', :as => "add_advert_comments"
  resources :topics
  resources :images, :only => [:index, :create]
  get 'blogs/:tag', to: 'topics#list', as: :tag
  match 'profile/:name' => 'topics#profile', :as => "user"

  root :to => 'adverts#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	attr_accessible :title, :body, :tag_list
	belongs_to :user
	acts_as_taggable_on :tags
	default_scope order("created_at DESC")
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]

  def new
    @topic = Topic.new
    respond_to do |format|
      format.js{}
      format.json{}
      format.html # index.html.erb
    end
  end
  
  def create
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    respond_to do |format|
      if @topic.save
        format.html{redirect_to @topic}
      else
        render action: "new"
      end
    end
  end  

  def show
  	@topic = Topic.find(params[:id])
  end
  
  def list
    @tags = Topic.tag_counts_on(:tags)
    if params[:tag].blank?
      @topics_last = Topic.paginate(:page => params[:page_last], :per_page => 9)
    else
      @topics_last = Topic.tagged_with(params[:tag]).paginate(:page => params[:page_last], :per_page => 9)
    end
#    @topics_tags = Topic.paginate(:page => params[:page_tags], :per_page => 4)
  end
  
  def profile
    @user = User.find_by_name params[:name]
    @adverts = @user.adverts
    @topics = @user.topics
    #TODO if current_user then edit profile
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/list.html.haml
.invert
	%h1 Последнее в блогах:
.pre_news
	= render :partial => "adverts/topic", :collection => @topics_last
%center
	= will_paginate @topics_last, :param_name => :page_last

- content_for :sidebar do
	Теги:
	%br
	-tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class|
		= link_to tag.name+', ', tag_path(tag.name), :class => css_class
	%hr.hr_dashed
	%center
		= link_to "Создать запись", new_topic_path, :class => 'ff green'

app/views/topics/new.html.erb
<%= include_imperavi_stylesheet %>
<%= include_imperavi_javascript %>
<%= imperavi :topic_body, 
            :lang => 'ru', :paths => {
    :images => {
      # Path to upload handler
      :upload => images_path,
      # Path to list of images
      :list   => images_path(:format => :json)
    }
  }
%>

<%= form_for :topic, {:url => topics_path, :html => { :multipart => true }} do |f| %>
<p>
<%= f.label "Заголовок:" %>
<br>
  <%= f.text_field :title%>
</p>

<ul id="myTags">
    <!-- Existing list items will be pre-added to the tags -->
    <li>Tag1</li>
    <li>Tag2</li>
</ul>


<redactor>
<p>
  <%= f.label 'body', "содержание:" %><br />
  <%= f.text_area :body , :rows=>10, :width=>"60%" %>
</p>
</redactor>
<br>
<%= submit_tag("Добавить", :class=>"ff blue") %>
<% end %>

app/views/topics/profile.html.haml
-content_for :sidebar do
	%a.comment-img{:href => "#non"}
		%img{:alt => "", :height => "50", :src => "http://skoda.avtokomplex.ru/i/head/skdlogo.jpg", :width => "50"}/
	%p{:style => "padding-top:0px;", :width => "150"}
		%span.bolder= @user.name
		%br
		%span.small_text Автокарма 0.560
	%hr.hr_dashed
	%p У пользователя интересные статьи и актуальные объявления, тогда отблагодарите его плюсом для автокармы. Если же пользователь оскорбил вас, то осудите его жирным минусом.
	%center
		%a.ff.green{:href => "#"} +
		%a.ff.red{:href => "#"} -
	%hr.hr_dashed

.invert
	%h1 Последние объявления:
%hr.hr_dashed
= render :partial => "adverts/adv", :collection => @adverts
%hr.hr_dashed
%br	 
.invert
	%h1 Последнее в блогах:
.pre_news
	= render :partial => "adverts/topic", :collection => @topics

app/views/topics/show.html.erb
<h1> <%= @topic.title %> </h1>
<br>
<br>
<redactor>
<article> 
<%= @topic.body.html_safe %>
</article>
</redactor>
 <br>
Теги: <%= raw @topic.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>

app/views/topics/show.js.erb
alert("dasasd");