config/routes.rb
Motorika::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users
  resources :uploads, :except => [:index, :create]
  match 'addphoto/:id' => 'uploads#index', :as => "uploads", :via => [:get]
  match 'addphoto/:id' => 'uploads#create', :as => "uploads", :via => [:post]
  resources :adverts
  match 'about' => 'application#about'
  match 'alladverts' => 'adverts#list', :as => "alladverts"
  match 'blogs' => 'topics#list', :as => "alltopics"
  match 'add_advert_comments' => 'adverts#add_comment', :as => "add_advert_comments"
  resources :topics
  resources :images, :only => [:index, :create]
  get 'blogs/:tag', to: 'topics#list', as: :tag
  match 'profile/:name' => 'topics#profile', :as => "user"

  root :to => 'adverts#index'

end

app/models/advert.rb
# coding: utf-8
class Advert < ActiveRecord::Base
	has_many :uploads, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	belongs_to :acompany
	belongs_to :amodel
	belongs_to :user
	attr_accessible :acompany_id, :amodel_id, :year, :price, :description,
		 :gear, :region, :contacts, :user_id
	acts_as_commentable
	default_scope order("created_at DESC")

	def self.search_by(params)
		gear = []

		
		# regions = []
		# regions << 0 if params[:region1]
		# regions << 1 if params[:region2]
		# regions << 2 if params[:region3]
		# regions << 3 if params[:region4]
		# regions << 4 if params[:region5]
		# regions << 5 if params[:region6]

		gear << 1 if params[:auto]
		gear << 2 if params[:manual]		

		params[:price1] = 0 if params[:price1].blank?
		params[:price2] = 1000000 if params[:price2].blank?	
		params[:year1] = 0 if params[:year1].blank?
		params[:year2] = 2100 if params[:year2].blank?
		case params[:sort]
		when "1"
			a = Advert.unscoped.order("created_at DESC")	
		when "-1"
			a = Advert.unscoped.order("created_at ASC")
		when "2"
			a = Advert.unscoped.order("price DESC")
		when "-2"
			a = Advert.unscoped.order("price ASC")
		when "3"
			a = Advert.unscoped.order("year DESC")
		when "-3"
			a = Advert.unscoped.order("year ASC")
		else 
			a = Advert.unscoped.order("created_at DESC")
		end
		a = a.where(acompany_id: params[:advert_acompany_id]) if !params[:advert_acompany_id].blank?
		a = a.where(amodel_id: params[:advert][:amodel_id]) if !params[:advert].blank? && !params[:advert][:amodel_id].empty?
		# a = a.where(region: regions) if !regions.empty?
		a = a.where(gear: gear) if !gear.empty?
		a = a.where(year: params[:year1].to_i..params[:year2].to_i)
		a = a.where(price: params[:price1].to_i*1000..params[:price2].to_i*1000)

		return a
	end

end

app/controllers/adverts_controller.rb
# coding: utf-8
class AdvertsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]
  
  def index
    @adverts = Advert.last(9).reverse
    @topics = Topic.last(9).reverse
  end
  
  def show
    @advert = Advert.find params[:id]
    @comments = @advert.comment_threads
  end
  
  def list
    @adverts = Advert.search_by(params)
    @acompanies = Acompany.all
    if !params[:acompany].nil? && !params[:acompany].empty?
      @amodels = Acompany.find(params[:acompany]).amodels
    else
      @amodels = []
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json {render json: [{name: "Все модели", id: ""}]+@amodels.map{|x| x.to_js}}
      format.js {}
    end
  end
  
  def new
    @advert = Advert.new
    @acompanies = Acompany.all
    if !params[:acompany].nil? && !params[:acompany].empty?
      @amodels = Acompany.find(params[:acompany]).amodels
    else
      @amodels = []
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json {render json: @amodels.map{|x| x.to_js}}
    end
  end
  
  def create
    @advert = Advert.new(params[:advert])
    @advert.user = current_user
    respond_to do |format|
      if @advert.save
        format.html{redirect_to uploads_path(@advert.id)}
      else
        render action: "new"
      end
    end
  end  

  def edit
    @advert = Advert.find params[:id]
    if current_user == @advert.user
      @acompanies = Acompany.all
      if !params[:acompany].nil? && !params[:acompany].empty?
        @amodels = Acompany.find(params[:acompany]).amodels
      else
        @amodels = @advert.acompany.amodels
      end
      respond_to do |format|
        format.html # index.html.erb
        format.json {render json: @amodels.map{|x| x.to_js}}
      end
    else
      redirect_to '/'
    end
  end

  def update
    if current_user == @advert.user
      @advert = Advert.find params[:id]
      @advert.update_attributes params[:advert]
      redirect_to @advert
    else
      redirect_to '/' 
    end
  end

  def add_comment
    @advert = Advert.find(params[:id])
    @user_who_commented = current_user
    @comment = Comment.build_from( @advert, @user_who_commented.id, params[:comment] )
    @comment.save
    @comments = @advert.comment_threads
    respond_to do |format|
      format.js
    end
  end
  
end

app/helpers/adverts_helper.rb
# coding: utf-8
module AdvertsHelper
	def getGear(a)
		return "автоматическая" if a
		return "механическая"
	end
end

app/views/adverts/_adv.html.erb
<%= link_to adv do %>
<div class="pin">
<div class="pre_img">
<%if adv.uploads.empty? %>
  <img src="http://dribbble.s3.amazonaws.com/users/85772/screenshots/361576/trabant-dribbble.png">
<%else%>
  <%= image_tag(adv.uploads[0].upload.url(:small)) %>
<%end%>
</div>
	<div class="pre_adv">
  	 <p>
     <%=  "#{adv.acompany.name} #{adv.amodel.name}, #{adv.year}" %>  
    <br>
  	 КПП: <%=getGear adv.gear%><br></p>
  	 <h1><%=number_to_currency(adv.price, :unit => "руб.", :separator => " ", :delimiter => " ", :format => "%n %u", :precision => 0)%></h1>
	</div>
</div>
<% end %>

app/views/adverts/_comment.html.erb
<section class="comments">
  <article class="comment">
    <a class="comment-img" href="#non">
      <img src="http://lorempixum.com/50/50/people/1" alt="" width="50" height="50">
    </a>
    <div class="comment-body">
      <div class="text">
        <p><%= comment.body %></p>
      </div>
      <p class="attribution">Автор: <%=link_to comment.user.name, user_path(comment.user.name) %></p>
    </div>
  </article>
</section>​

app/views/adverts/_topic.html.erb
	 <h1><%= link_to topic.title, topic %></h1>
	 <span class="small_text"> 
	 	<%= distance_of_time_in_words(Time.new.to_i, topic.created_at.to_i) %>
	 	назад | Автор: <%= link_to topic.user.name, user_path(topic.user.name)%>
	 <br> Теги:
	 <%= raw topic.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
	</span>
	 <hr class="hr_dashed">

app/views/adverts/about.html.erb
<div class="invert"><p>"Моторика" - проект для автомобилистов, которые любят свои авто и уважительно относятся к другим участникам дорожного движения. Мы работаем для водителей Юга России: Астрахань и область, Волгоград и область, Краснодарский край, Республика Адыгея, Республика Калмыкия, Ростов-на-Дону и область. </p>
</div> <br>
   		 
	 
	 <h1>Цель проекта</h1>
	 <p>Создание здорового сообщества автомобилистов, которые любят драйв, но при этом стараются не нарушать ПДД. Взаимопомощь, обмен знаниями и лайфхаками, которые помогут сделать нашу автомобильную жизнь проще. </p>
	 <hr class="hr_dashed">
	 
	  <h1>Пользователь</h1>
	 <p>Ценная единица живого сообщества. На сайте нет разделения на пользователя-человека и пользователя-организацию, поскольку они имеют равные права и возможности. Каждый пользователь - уникальный юзер, который подчиняется системе рейтинга - "автокарма". У нас нет ограничений на добавление контента, поэтому создание нескольких аккаунтов - великая глупость. </p>
	 <hr class="hr_dashed">
	 
	 	  <h1>Автокарма</h1>
	 <p>Единица подсчета полезности пользователя и его авторитетности между другими участниками сообщества. Может быть получена за активность на сайте и потрачена в дальнейшем на дополнительные возможности. </p>
	 <hr class="hr_dashed">
	 
	 	  <h1>Сервисы</h1>
	 <p>Мы стараемся дорабатывать наше сообщество и добавлять новый функционал. На данный момент мы предоставляем три основных сервиса:<br><br>
	 1. Лента блогов<br>
	 Лента пользовательских находок, новостей, заметок, интересных материалов и вопросов к сообществу. Поиск по материалам происходит с помощью использования тегов, поэтому сайт не ограничен в рубрикации.<br><br>
	 
	  2. Объявления о продаже авто<br>
	 Удобная и простая доска объявлений, которая не имеет ограничений на количество добавляемой информации. Объявления публикуются моментально и на неограниченный срок.<br><br>
	 
	  3. Автомобильный бизнес<br>
	 Каталог автомобильных услуг со строгой рубрикацией и возможностью поиска по населенным пунктам.
	  </p>
	   <hr class="hr_dashed">
	  <h1>Сотрудничество</h1>
	 <p>Мы всегда рады сотрудничеству. Мы ждем от вас письма на нашу почту partners@motorica.me<br>
  	 Рекламу вы можете заказать без контактов с редакцией, через сервис <a href="">AdEasy</a>.
	 </p>

app/views/adverts/add_comment.js.erb
$('#list_comments').html("<%=j render partial: "comment", collection: @comments %>");
$('input.comm').val("");

app/views/adverts/edit.html.erb
<%= form_for @advert, {:url => adverts_path, :html => { :multipart => true }} do |f| %>

<%= f.label "Марка:  " %>
<%= f.collection_select(:acompany_id, @acompanies, :id, :name, {:prompt => "Выберите марку", :class=>"medium", :id=>"acompanies_select" }) %>
<%= f.label "Модель:  " %>
<%= f.collection_select(:amodel_id, @amodels, :id, :name, {:prompt => "Выберите модель", :class=>"medium", :id=>"advert_amodel_id" }) %>
<%#= f.collection_select(:amodel_id, @amodels, :id, :name) %>
<br>
<%= f.label 'year', "Год:" %>
<%= f.text_field :year, :size=>10, :class=>"tip", :title=>"пример: 2011"%>
<br>
  <%= f.label 'price', 'Цена в руб.:' %>
  <%= f.text_field :price, :size=>10, :class=>"tip", :title=>"пример: 600000 "%>
<br>
<p>
  <%= f.label 'descr', "Описание:" %><br />
  <%= f.text_area :description , :style=>"width:65%", :rows=>10 %>
</p>
<br>
<p>
  <%= f.label 'gear', "Коробка:" %>
  <%= f.select :gear, [["механическая", 1],["автоматическая", 2]]%>
<br>
<p>
  <%= f.label 'contacts', "Контакты:" %>
  <%= f.phone_field :contacts, :size=>50, :class=>"tip", :title=>"пример: тел. 123-45-78 Петр"%>
</p>
<%= submit_tag("Изменить", :class=>"btn success") %>
<%= link_to "Отменить", :back %>
<% end %>

app/views/adverts/index.html.haml
.invert
  %p
    "Моторика" - автомобильное сообщество Юга России. Если ты любишь машины, то мы ждем тебя в компании единомышленников. На сайте ты сможешь не только вести свой автоблог, но еще и посмотреть на предложения по продаже авто, найти услуги по ремонту и обслуживанию, задать вопросы и проконсультировать других участников.
    %br
      %a{:href => new_user_registration_path} Регистрируйся
      и стань частью Моторики.
%br
  .invert
    %h1 Последние объявления:
  = render :partial => "adv", :collection => @adverts
  %hr.hr_dashed
  %br
  .invert
    %h1 Последнее в блогах:
  .pre_news
    = render :partial => "topic", :collection => @topics
  .invert
    %p
      У вас автомобильный бизнес? Вы занимаетесь запчастями, ремонтом, продажей, выкупом автомобилей? Тогда
      %a{:href => new_user_registration_path} регистрируйтесь
      и получите возможность добавить свой услуги в наш каталог "Автомобильный бизнес", писать новости и привлекать потенциальных покупателей, а также Вы сможете оформить свою страницу и использовать ее как сайт-визитку.

app/views/adverts/list.html.erb
 <div class="invert" style="margin-bottom: 5px;">
     <h1>По вашим параметрам найдено <span id="size"><%="#{@adverts.size} #{Russian.p(@adverts.size, "объявление", "объявления", "объявлений")}"%></span> </h1>
 		  </div> 

<p id="adv_sort" class="small_text">Сортировать по <%= link_to_function "цене", 'if($("#sort").val() == 2){$("#sort").val(-2);}else{$("#sort").val(2);}$("#adv_form").submit()' %> / <%= link_to_function "году выпуска", 'if($("#sort").val() == 3){$("#sort").val(-3);}else{$("#sort").val(3);}$("#adv_form").submit()' %> / <%= link_to_function "дате добавления", 'if($("#sort").val() == 1){$("#sort").val(-1);}else{$("#sort").val(1);}$("#adv_form").submit()'%></p>

   <div id="list_adverts">
     <%= render :partial => "adv", :collection => @adverts %>
   </div>
	 
  
  <%content_for :sidebar do%>
  <center><a class="ff green" href="<%= new_advert_path %>">Добавить объявление</a></center>
	  <hr class="hr_dashed">
	  <br>
    
    <%= form_tag alladverts_path, {remote: true, id: 'adv_form'} do %>
    <h1>Поиск по параметрам</h1>
    <hr class="hr_dashed">	
    <h3>Марки и модель:</h3><p>
      <%=select_tag :advert_acompany_id, options_for_select( @acompanies.map { |cp| [cp.name, cp.id] }), {prompt: 'Все марки', :class=>"medium", :id=>"advert_acompany_id" } %>
      
      <select id="advert_amodel_id" name="advert[amodel_id]">
        <option value="">Все модели</option>
      </select>
      <%#= collection_select(:advert_amodel, :id, @amodels, :tag, :name) %>
         
    <hr class="hr_dashed">
    
			<h3>КПП:</h3><p>
			<span id="checkbox">
        <%= check_box_tag(:auto) %>
        <%= label_tag(:auto, "Автоматическая") %>
        <br>
        <%= check_box_tag(:manual) %>
        <%= label_tag(:manual, "Механическая") %>
        <br>
			</span>
		  </p>
      
      <hr class="hr_dashed">
      <h3>Год выпуска:</h3><p>
      от <%= text_field_tag :year1, nil, {class: "text", placeholder: "2006"}%>
      до <%= text_field_tag :year2, nil, {class: "text", placeholder: "2011"}%>
      </p>
      
      <hr class="hr_dashed">
      <h3>Цена:</h3><p>
        от <%= text_field_tag :price1, nil, {class: "text", placeholder: "200"}%>
        до <%= text_field_tag :price2, nil, {class: "text", placeholder: "300"}%><br>
      <span class="small_text">Цена указывается в тысячах рублей</span>
      </p>

      <hr class="hr_dashed">
            <%= hidden_field_tag :sort, 1 %>
    <center>
      <%= submit_tag("Применить параметры", :class=>"ff blue") %>
    </center>
    <hr class="hr_dashed">
    <% end %>
<% end %>

app/views/adverts/list.js.erb
$('#list_adverts').html("<%=j render partial: "adv", collection: @adverts %>");
$("#size").html("<%= "#{@adverts.size} #{Russian.p(@adverts.size, "объявление", "объявления", "объявлений")}" %>");
$(".grid_8").effect( "highlight", {color:"#5F9900"}, 500 );

app/views/adverts/new.html.erb
<%= form_for :advert, {:url => adverts_path, :html => { :multipart => true }} do |f| %>

<%= f.label "Марка:  " %>
<%= f.collection_select(:acompany_id, @acompanies, :id, :name, {:prompt => "Выберите марку", :class=>"medium", :id=>"acompanies_select" }) %>
<%= f.label "Модель:  " %>
<select id="advert_amodel_id" name="advert[amodel_id]">
</select>
<%#= f.collection_select(:amodel_id, @amodels, :id, :name) %>
<br>
<%= f.label 'year', "Год:" %>
<%= f.text_field :year, :size=>10, :class=>"tip", :title=>"пример: 2011"%>
<br>
  <%= f.label 'price', 'Цена в руб.:' %>
  <%= f.text_field :price, :size=>10, :class=>"tip", :title=>"пример: 600000 "%>
<br>
<p>
  <%= f.label 'descr', "Описание:" %><br />
  <%= f.text_area :description , :style=>"width:65%", :rows=>10%>
</p>
<br>
<p>
  <%= f.label 'gear', "Коробка:" %>
  <%= f.select :gear, [["механическая", 1],["автоматическая", 2]]%>
<br>
  <%= f.label 'contacts', "Контакты:" %>
  <%= f.phone_field :contacts, :size=>50, :class=>"tip", :title=>"пример: тел. 123-45-78 Петр"%>
</p>
<%= submit_tag("Добавить", :class=>"ff blue") %>
<% end %>

app/views/adverts/show.html.erb
<div class="invert">
     <h1><%="#{@advert.acompany.name} #{@advert.amodel.name}, #{@advert.year}"%></h1>
      <% if @advert.user==current_user %>
      <%= link_to "Изменить фото", uploads_path(@advert.id) %>
      &nbsp;&nbsp;&nbsp;
 		  <%= link_to "Изменить объявление", edit_advert_path(@advert.id) %>
      <%end%>
</div>


<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
  <%@advert.uploads.each_with_index do |img, index|%>
  <%if index==0%>
    <div class="active item">
    <%= image_tag img.upload.url(:normal), class: 'photo'%>
    </div>
    <%else%>
    <div class="item">
        <%= image_tag img.upload.url(:normal), class: 'photo'%>
    </div>
    <%end%>
  <%end%>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
	 <hr class="hr_dashed">


	 <p><span class="bolder">Пользователь: <%=link_to @advert.user.name, user_path(@advert.user.name)%></span></a><br>
	 <span class="bolder">КПП:</span> <%=getGear @advert.gear%><br>
   <span class="bolder">Основная информация:</span> <%= @advert.description %><br>
<span class="bolder">Контакты для связи:</span> <%= @advert.contacts %><br>
   		 
   <div class="invert">
     <h1><center><%=number_to_currency(@advert.price, :unit => "руб.", :separator => " ", :delimiter => " ", :format => "%n %u", :precision => 0)%></center></h1>
 		  
</div>
	 <br>

   <div id="list_comments">
     <%= render :partial => "comment", :collection => @comments %>
   </div>

<%= form_for :comment, {:url => add_advert_comments_path, :remote => true, :html => { :multipart => true }} do |f| %>

<%= text_field_tag :comment, nil, placeholder: "Напишите свой вопрос или предложение...", :width=>"100%", class: "comm"%>
<%#= f.text_area :comment, {placeholder: "Напишите свой вопрос или предложение...", :width=>"100%", :class=>"comm", rows: 2, cols: 60} %>
<%= hidden_field_tag :id, @advert.id %>
<%= submit_tag("Добавить +", :class=>"ff green") %>
<% end %>